baseURL = 'https://jeezluisjorge.com/'
languageCode = 'en'
title = 'Christopher Luis-Jorge'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 18
disableHugoGeneratorInject = true

[params]
ava = "/img/clj.jpg"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
