languageCode = "en-us"
title = "Christopher Luis-Jorge"
baseURL = "https://www.jeezluisjorge.com/"
theme = "../.."

[params.portfolio]
    title = "Publications"
    foldername = "publications"
    findoutmoretext = "Read more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = ""
    disqus = ""