languageCode = "en-us"
title = "Christopher Luis-Jorge"
baseURL = "http://www.jeezluisjorge.com/"
theme = "../.."

[params.portfolio]
    title = "Publications"
    foldername = "publications"
    findoutmoretext = "Read more"

[params.settings]
    googleanalytics = ""
    disqus = ""