baseURL = "https://www.jeezluisjorge.com"
title = "Christopher Luis-Jorge"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  customFooterHTML = '''
  <a href="mailto:chrisluisjorge@gmail.com" target="_blank">Email me</a>
  '''
  description = "Writer and Musician"
  favicon = "images/favicon-16x16.png"
  avatarURL = "images/clj.jpg"
  AvatarAltText = "me"
  avatarSize = "size-m"
  customHeadHTML = ""
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/jeez_luis_jorge"},
    {name = "email", url = "mailto:chrisluisjorge@gmail.com"},
    {name = "youtube", url = "https://www.youtube.com/@thespookinghour6227"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
