baseURL = "https://www.jeezluisjorge.com"
title = "Christopher Luis-Jorge"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  customFooterHTML = '''
  <u><a href="mailto:chrisluisjorge@gmail.com" target="_blank">Email me</a></u>
  '''
  description = "Writer + Musician"
  favicon = "favicon.ico"
  avatarURL = "images/clj.jpg"
  AvatarAltText = "me"
  avatarSize = "size-m"
  customHeadHTML = '''
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
'''
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/jeezluisjorge"},
    {name = "email", url = "mailto:chrisluisjorge@gmail.com"},
    {name = "youtube", url = "https://www.youtube.com/channel/UCQvrWHEAcDO3N9L5_GNB9Ew"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    name = "Email Me"
    url = "mailto:chrisluisjorge@gmail.com"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
